---
title: "Lbs poured per year"
author: "Edward Yu"
date: "July 23, 2019"
output:
  # pdf_document:
  #     toc: true
  #     toc_depth: 2
  #     df_print: kable
  #     citation_package: natbib
  html_document:
      theme: flatly
      highlight: tango
      toc: true
      toc_float:
        collapsed: true
      toc_depth: 3
      df_print: paged
      code_folding: show
      # fig_width: 7
      # fig_height: 6
      # fig_caption: true
      # citation_package: natbib
# bibliography: bib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo    = TRUE,
                      error   = FALSE,
                      message = FALSE,
                      warning = FALSE)

if(!require(tidyverse)) install.packages("tidyverse")
library(tidyverse)

# rm(list=ls())
setwd("D:/Code/R/historical.MAL")

y <- read_csv("data/cleanedMAL.csv", col_names=T) %>% 
  select(-X1)
```

# Lbs poured per year
Simple list of values reporting lbs of metal poured per year in the melt lab. Dataframes grouped both by year and by year and alloy.

```{r}
glimpse(y)

# select columns
yy <- y %>% 
  mutate(year = format(date.received, "%Y")) %>%
  mutate(year = factor(year)) %>% 
  select(year, alloy, alloy.lbs) %>% 
  drop_na()
  
# lbs per year  
yy %>% 
  group_by(year) %>% 
  summarise(total.lbs = sum(alloy.lbs))

# by alloy
yy %>% 
  group_by(year, alloy) %>% 
  summarise(total.lbs = sum(alloy.lbs))

```

# Graphical representation
Plots of above data. 
Facet graph removes low quantity pours to reduce clutter.  

```{r}
yy %>% 
  ggplot(aes(x=year, y=alloy.lbs))+
  geom_bar(stat="identity") + 
  ggtitle("Lbs poured vs year") + 
  xlab("Year") + 
  ylab ("Lbs poured")+
  theme(axis.text.x = element_text(angle=-70,vjust=0.5,hjust=0))

yy %>%
  ggplot(aes(x=year, y=alloy.lbs, fill=alloy))+
  geom_bar(stat="identity") +
  ggtitle("Lbs poured vs year by alloy") +
  xlab("Year") +
  ylab ("Lbs poured")+
  theme(axis.text.x = element_text(angle=-70,vjust=0.5,hjust=0))


yy %>% 
  filter(alloy != "stainless") %>% 
  filter(alloy != "simo") %>% 
  filter(alloy != "brass") %>% 
  filter(alloy != "white iron") %>% 
  filter(alloy != "copper") %>% 
  ggplot(aes(x=year, y=alloy.lbs))+
  geom_bar(stat="identity") + 
  facet_wrap(~alloy)+
  ggtitle("Lbs poured vs year by alloy") + 
  xlab("Year") + 
  ylab ("Lbs poured") +
  theme(axis.text.x = element_text(angle=-70,vjust=0.5,hjust=0))

```

